### PR TITLE
Fix history id generation for CucumberJVM scenarios with same feature file name

### LINKED ISSUE #570: [allure-cucumber6-jvm] Missing test cases in a report for features with same filenames.
**Describe the bug**
Executing multiple feature files with same filenames in a single suite causes some of the results to be missing. This can be clearly seen in fragmented Allure timeline.

Looking at the generated results each test has a container.json file, however, some of them are missing results.json. Looking into more detail, tests with same feature filename have identical child UUID. This probably causes the results to be overwritten.

**To Reproduce**
Please use my mock test suite - https://github.com/algirdasN/Allure_bug_replication
1. run tests using maven - 'mvn clean test'
2. create allure test - 'allure serve .\target\allure-results'

**Expected behavior**
Each test case should be in the report.

**Screenshots**
image

image

image

image

image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: latest

### PR DESCRIPTION
**Pull request by prtnv**
Fixes #570 

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by prtnv** [comment]
@baev can you review this PR?

File: allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java [hunk 1]
```diff
@@ -99,6 +100,9 @@ public class AllureCucumber6Jvm implements ConcurrentEventListener {
 
     private static final String TXT_EXTENSION = ".txt";
     private static final String TEXT_PLAIN = "text/plain";
+    private static final char CUCUMBER_RESOURCE_SEPARATOR_CHAR = '/';
+    private static final String CUCUMBER_WORKING_DIR = System.getProperty("user.dir")
```
Comment (baev) [inline allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java:104]: maybe use `new File("")` instead?

File: allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java [hunk 2]
```diff
@@ -279,12 +283,19 @@ private String getHookStepUuid(final HookTestStep step) {
...
-        final String testCaseLocation = testCase.getUri().toString()
-                .substring(testCase.getUri().toString().lastIndexOf('/') + 1)
-                + ":" + testCase.getLocation().getLine();
+        final String testCaseLocation = getTestCaseUri(testCase) + ":" + testCase.getLocation().getLine();
         return md5(testCaseLocation);
     }
 
+    private String getTestCaseUri(final TestCase testCase) {
+        final String testCaseUri = testCase.getUri().toString();
+        final int workingDirIdx = testCaseUri.indexOf(CUCUMBER_WORKING_DIR);
```
Comment (baev) [inline allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java:292]: can we use `startsWith()` instead of `indexOf` ( if we use `new File("").toUri().toString()` instead of CUCUMBER_WORKING_DIR ) ?

**Review by baev — CHANGES_REQUESTED** [review]

File: allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java (hunk 1 above)
Comment (prtnv) [reply allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java]: I found that Cucumber uses `io.cucumber.core.resource.Resources$UriResource`to get the test case uri, which in turn uses `Path` instead of `File`. Because Path#toUri and File#toURI gets some different result, I did it with Paths.get("")

File: allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java (hunk 2 above)
Comment (prtnv) [reply allure-cucumber6-jvm/src/main/java/io/qameta/allure/cucumber6jvm/AllureCucumber6Jvm.java]: Done. Thanks! But I left the `CUCUMBER_WORKING_DIR` constant in place so as not to create a new object every time

**Review by baev — APPROVED** [review]
