### PR TITLE
Fixes #291 - support for multiple Examples blocks per Scenario Outline

### LINKED ISSUE #291: Exception occurred in cucumber2jvm/cucumber3jvm versions when running Scenario Outline Examples
When Executing **Scenario Outline** Examples in cucumber in the following versions i.e cucumber2jvm/cucumber3jvm,  I'm getting an exception as given below.

After execution first example scenario, i'm getting the below exception script is not able to run the next example 

### Issue Log 

```
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm.getExamplesAsParameters(AllureCucumber3Jvm.java:233)
        at io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm.handleTestCaseStarted(AllureCucumber3Jvm.java:119)
        at cucumber.runner.EventBus.send(EventBus.java:28)
        at cucumber.runner.TestCase.run(TestCase.java:37)
        at cucumber.runner.Runner.runPickle(Runner.java:44)
        at cucumber.runtime.Runtime.runFeature(Runtime.java:120)
        at cucumber.runtime.Runtime.run(Runtime.java:106)
        at cucumber.api.cli.Main.run(Main.java:35)
        at cucumber.api.cli.Main.main(Main.java:18)
```

### Dependency Configuration & Plugin

```
buildscript {
    repositories { jcenter() }
    dependencies {
        classpath "io.qameta.allure:allure-gradle:2.5"
    }
}

apply plugin: 'io.qameta.allure'

allure 
{
        aspectjweaver = true
         version = '2.7.0'
        useCucumberJVM 
   {
        version = '2.7.0'
    }
}

task cucumber(type: Test) {
{

            args = ['--glue','Steps',
                    '--plugin', 'io.qameta.allure.cucumber2jvm.AllureCucumber2Jvm',
                    '--tags', tag,
                    "src/test/resources/features"
            ]
}

dependencies 
{
compile group: 'io.qameta.allure', name: 'allure-cucumber2-jvm', version: '2.7.0'
}

testCompile ("io.cucumber:cucumber-java:2.3.1”)
testCompile ("io.cucumber:cucumber-junit:2.3.1")
compile     ("io.cucumber:cucumber-core:2.3.1")
testCompile ("io.cucumber:gherkin:4.1.3”)
```

### PR DESCRIPTION
**Pull request by letsrokk**
[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

### Context
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

Fixes #291 - adds support for multiple Examples blocks per Scenario Outline (for Cucumber JVM 3.x and 4.x adapters)

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

File: allure-cucumber4-jvm/src/main/java/io/qameta/allure/cucumber4jvm/AllureCucumber4Jvm.java [hunk 1]
```diff
@@ -40,12 +40,7 @@
 
 import java.io.ByteArrayInputStream;
 import java.nio.charset.Charset;
-import java.util.Deque;
-import java.util.LinkedList;
-import java.util.List;
-import java.util.Objects;
-import java.util.Optional;
-import java.util.UUID;
+import java.util.*;
```
Comment (baev) [inline allure-cucumber4-jvm/src/main/java/io/qameta/allure/cucumber4jvm/AllureCucumber4Jvm.java]: revert this change

Comment (letsrokk) [reply allure-cucumber4-jvm/src/main/java/io/qameta/allure/cucumber4jvm/AllureCucumber4Jvm.java]: done + fixed a few pmd and checkstyle warnings

**Comment by QA2Dev** [comment]
Please let me know allureCucumber3JVM build version to be added in dependency, for which Fix is given.

dependencies
{
compile group: 'io.qameta.allure', name: 'allure-cucumber2-jvm', version: '????'
}
